global:
  resolve_timeout: 5m

route:
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default'

receivers:
- name: 'default'
  webhook_configs:
  - url: 'http://localhost:9090/alert'

